services:
  backend:
    build:
      context: ./quotesync-backend
      dockerfile: Dockerfile
      args:
        FRONTEND_PORT: $FRONTEND_PORT
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./quotesync-backend:/app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./quotesync-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./quotesync-frontend:/app
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
