# Generated by Django 4.2.3 on 2024-11-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre', max_length=1024, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre', max_length=1024, unique=True)),
                ('author', models.ForeignKey(blank=True, help_text='Autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='quotes.author')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(help_text='Título', unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción', max_length=1024, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título', max_length=1024)),
                ('body', models.TextField(blank=True, help_text='Cita', null=True)),
                ('archive', models.BooleanField(default=False, help_text='Archivada')),
                ('created', models.DateField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, help_text='Fecha de actualización')),
                ('hash', models.SlugField(blank=True, help_text='Hash', null=True)),
                ('book', models.ForeignKey(blank=True, help_text='Libro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.book')),
                ('tags', models.ManyToManyField(blank=True, help_text='Etiquetas', related_name='quotes', to='quotes.tag')),
            ],
            options={
                'ordering': ('created', 'title'),
            },
        ),
    ]
